FROM docker.io/postgres:latest

LABEL Leonardo Viana <leonardoviana00@hotmail.com>

ENV POSTGRES_PASSWORD=flyway
ENV POSTGRES_DB=flyway_teste
ENV POSTGRES_USER=flyway

VOLUME [ "/var/lib/postgresql/data" ]

EXPOSE 5432

