version: "3.5"

services:

  #######################################
  # Postgres
  #######################################

  db:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: "postgres:12.2-alpine"
    env_file: ./docker/env/db.env
    restart: always
    volumes:
      - ./postgres/db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - flyway-net

  #######################################
  # Flyway
  #######################################

  flyway:
    image: flyway/flyway:6.4.1-alpine
    restart: on-failure
    environment:
      FLYWAY_EDITION: community
    command: migrate
    volumes:
      - ./migration:/flyway/sql/
      - ./config/flyway.conf:/flyway/conf/flyway.conf
    links:
      - db
    depends_on:
      - db
    networks:
      - flyway-net
  
  #######################################
  # PgAdmin
  #######################################

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: flyway00@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    links:
      - db
    depends_on:
      - db
    ports:
      - 5050:80
    networks:
      - flyway-net
    
# volumes:
  # db-data:

networks:
  flyway-net:
    driver: bridge
